# Generated by Django 5.0.7 on 2024-08-02 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dept_no',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
            preserve_default=False,
        ),
    ]
