# Generated by Django 5.0.7 on 2024-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_dept_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
